version: '3.7'
services:
  app:
    image: node:10
    volumes:
      - ../../:/app
    working_dir: /app
    command: /app/.buildkite/publish/run.sh
    environment:
      - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
      - NPM_TOKEN
      - GITHUB_TOKEN
      - UPDATE_STUDIO
      - BUILDKITE
      - PUBLISH_BUILD=true
      - REDIS_URL
    depends_on:
      - postgres
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma

    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
