version: "3.7"
services:
  app:
    image: node:10
    volumes:
      - ../../:/app
    working_dir: /app
    command: /app/.buildkite/publish/run.sh
    environment:
      - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
      - TEST_MYSQL_URI=mysql://prisma:prisma@mysql:3306/prisma-dev
      - NPM_TOKEN
      - GITHUB_TOKEN
      - UPDATE_STUDIO
      - BUILDKITE
      - BUILDKITE_TAG
      - PUBLISH_BUILD=true
      - REDIS_URL
      - MIGRATE_COMMIT
      - PRISMA_CLIENT_JS_COMMIT
      - PRISMA2_COMMIT
      - DEVELOPMENT_ENVIRONMENT_COMMIT
    depends_on:
      - postgres
      - mysql

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    volumes:
      - mysql:/var/lib/mysql/data

volumes:
  postgres:
  mysql:
